In [1]:
import plotly.express as px 
import pandas as pd

In [2]:
# Read in mov means
df = pd.read_csv("/Users/reem/GtoAprobs_new.tsv", delimiter="\t")
df.head()

   Unnamed: 0 Mutational_Context  Molnupiravir    Normal
0           0            A[G>A]A      0.033405  0.087632
1           1            A[G>A]C      0.047585  0.061329
2           2            A[G>A]G      0.026441  0.107071
3           3            A[G>A]T      0.065896  0.092315
4           4            C[G>A]A      0.021137  0.023764

In [14]:
import plotly.graph_objects as go
# Plot proprtions of G>A mutations fro MOV vs Normal samples

fig = fig = go.Figure(data=[go.Bar(name='Molnupiravir', x=df['Mutational_Context'], y=df['Molnupiravir']), go.Bar(name='Normal', x=df['Mutational_Context'], y=df['Normal'])], 
                      layout=go.Layout(title='G-to-A mutation spectrum by trinucleotide context', yaxis=dict(range=[0,0.3])))

fig.update_layout(margin=dict(l=20, r=20, t=50, b=20), legend=dict(x=0.8, y=0.95))
fig.write_image("/Users/reem/molnupiravir_paper/Figures/mov_vs_normal_ga_proportions.pdf")
fig.show()

In [11]:
ctprobs = pd.read_csv("/Users/reem/CtoTprobs_new.tsv", delimiter="\t")
ctprobs.head()

   Unnamed: 0 Mutational_Context  Molnupiravir    Normal
0           0            A[C>T]A      0.241418  0.171756
1           1            A[C>T]C      0.059448  0.057856
2           2            A[C>T]G      0.033972  0.050892
3           3            A[C>T]T      0.116821  0.126818
4           4            C[C>T]A      0.052645  0.068889

In [13]:
# Plot proprtions of C-to-T mutations fro MOV vs Normal samples

fig = fig = go.Figure(data=[go.Bar(name='Molnupiravir', x=ctprobs['Mutational_Context'], y=ctprobs['Molnupiravir']), go.Bar(name='Normal', x=ctprobs['Mutational_Context'], y=ctprobs['Normal'])], 
                      layout=go.Layout(title='C-to-T mutation spectrum by trinucleotide context', yaxis=dict(range=[0,0.3])))

fig.update_layout(margin=dict(l=20, r=20, t=50, b=20), legend=dict(x=0.8, y=0.95))
fig.write_image("/Users/reem/molnupiravir_paper/Figures/mov_vs_normal_ct_proportions.pdf")
fig.show()

In [5]:
fig = px.bar(df, x='Mutational_Context', y='Normal',
    title='Non-MOV mean G>A proportions by mutation context')
fig.layout.yaxis.range=[0,0.3]
fig.show()

In [ ]:
# Plot the last row in the Mov_dataframe "means_row" vs GtoA context
context_cols = [col for col in df.columns if col not in ["seqName", "LLR","Unnamed: 0"]]
mean_row = df[df['seqName'] == 'Mean'].iloc[0]
#print(mean_row)
plot_df = mean_row[context_cols].reset_index()
plot_df.columns = ['Context', 'Mean']
fig = px.bar(plot_df, x='Context', y='Mean',
    title='Mean Values of Mutation Contexts')
fig.show()

In [ ]:
# Same plot with the Non_Mov dataframe showing the discrepancy in the number of GtoA mutations across sequences
df_low = pd.read_csv("/Users/reem/Mov/nextclade_results/Normal_means.tsv",delimiter="\t")
#df_low.head(10)
context_cols = [col for col in df_low.columns if col not in ["seqName", "LLR","Unnamed: 0"]]
mean_row = df_low[df_low['seqName'] == 'Mean'].iloc[0]
#print(mean_row)
plot_df_low = mean_row[context_cols].reset_index()
plot_df_low.columns = ['Context', 'Mean']
fig = px.bar(plot_df_low, x='Context', y='Mean',
    title='Mean Values of Normal Mutation Contexts')
fig.show()